### ISSUE TITLE
LiveSplit Overlay

### ISSUE THREAD

**Issue by CryZe** [speedcontrol/nodecg-speedcontrol#10]
Hey, so we are working on LiveSplit One, which is the cross-platform version of LiveSplit. Underneath, we are developing a library called livesplit-core, which provides all the information and functionality needed to write a timer application with any kind of UI on top with very little effort. And since the library is incredibly portable and comes with bindings for 11 languages including JavaScript, it should be super easy to hook this into NodeCg.

**Comment by zoton2** [comment]
Update: we now have an basic implementation of livesplit-one in the code, will expand on it at a later date hopefully.
