### ISSUE TITLE
AGDQ timer issues

### ISSUE THREAD

**Issue by Planks** [speedcontrol/nodecg-speedcontrol#11]
Reminder after AGDQ is finished to follow up with Lange/Vulajin about what the cause of the timer problem was because it probably affects us too

https://www.reddit.com/r/speedrun/comments/6l1052/the_sgdq2017_stopwatch_on_screen_is_running_too/

**Comment by zoton2** [comment]
Very late update: issue was they were using their own code to run a timer and their own code wasn't very good, they went back to nano-timer for the rest of that event and then switched over to livesplit-core for AGDQ2017, which we have done as well.
