### ISSUE TITLE
Automatically normalise uploaded video media

### ISSUE THREAD

**Issue by Planks** [speedcontrol/nodecg-speedcontrol#112]
**Prerequisites**
Requires [ffmpeg-normalize](https://github.com/slhck/ffmpeg-normalize) and [ffmpeg](https://ffmpeg.org/download.html) installed. 

**Use case**
ffmpeg-normalize simplifies using ffmpeg to normalise audio levels in video. Normally this takes several steps and is difficult to script. I use ffmpeg-normalize before uploading each glitch intermission and video advert, it'd be a nice QOL improvement for nodecg to run this command for me after an upload completes

The command I normally use is as follows, it supports wildcards. It will need more arguments to force an output folder, and the source file is not automatically deleted.

`ffmpeg-normalize *.mp4 -ext mp4 -c:a aac`

**Comment by zoton2** [comment]
I don't think this should be a feature for this bundle but for other bundles, so will close this and open a new one in a more appropriate place.
