### ISSUE TITLE
Allow importing of custom Oengus data

### ISSUE THREAD

**Issue by nicnacnic** [speedcontrol/nodecg-speedcontrol#119]
Allow the option to import custom data from Oengus submissions, such as layouts, hosts, etc... Pretty much the same thing as the Horaro schedule import tool but for Oengus.

**Comment by zoton2** [comment]
[Already done](https://github.com/speedcontrol/nodecg-speedcontrol/blob/master/READMES/Schedule-Formatting.md#custom-data-1), was released in v2.4.0. Or am I misunderstanding your request?

**Comment by nicnacnic** [comment]
You're totally right, didn't see the page for that.
