### ISSUE TITLE
Improve big red button labelling

### ISSUE THREAD

**Issue by Planks** [speedcontrol/nodecg-speedcontrol#16]
This is a collaborative issue between button team and layout team.

There has been confusion during races (every time) about what big red button applies to which runner

This can be mitigated with some labelling.

1) The buttons should be labelled 1, 2, 3 and 4
2) The player icon on the layouts should be replaced with numerical icons, representing what button the runner needs to press a little like this 
![capture](https://user-images.githubusercontent.com/16325321/36342111-4b39d548-13f1-11e8-91b3-a1b8ce6e9901.PNG)

**Comment by zoton2** [comment]
Wasn't really relevant to this bundle, and I've done this idea for ESA Summer 2018.
