### ISSUE TITLE
‘Quick add duplicate’ button

### ISSUE THREAD

**Issue by Planks** [speedcontrol/nodecg-speedcontrol#21]
A button on the run card in the schedule editor to duplicate the current run directly after the current run, so we can quickly add bonus content

**Comment by zoton2** [comment]
There is some issues that might arise from this in our esas18-layouts bundle, need to check code there while trying to work on this too.

**Comment by zoton2** [comment]
Has been done in the esas18 branch.

**Comment by zoton2** [comment]
We would also like a prompt to ask if the user would like to change the category when cloning, which is usually what you want to do while making a bonus run.
