### ISSUE TITLE
Speedcontrol handling of sponsored content

### ISSUE THREAD

**Issue by Planks** [speedcontrol/nodecg-speedcontrol#27]
We need to be able to put #Sponsored or [Sponsored] into a column in the schedule for Summer, and for Speedcontrol to correctly pass on this information to:

Twitch Title
Youtube (setting the 'this video contains a paid endorsement' flag - FAQ at https://support.google.com/youtube/answer/154235?hl=en-GB )

**Comment by zoton2** [comment]
My plan for this is to add a way of having custom information on the schedule import, because I need something similar for other marathons too.

**Comment by zoton2** [comment]
Added stuff to the ESAController file to get the sponsored flag if it's set as custom data in the schedule, and passes it along to that chain. Still need to make it add `#sponsored` to the Twitch title and add something to the highlights (description or title again?).

**Comment by zoton2** [comment]
Added `#sponsored` to Twitch stream title and highlight title.

**Comment by zoton2** [comment]
The column we have is called "Info" and it needs to set the run as a sponsored run whenever the contents of that column for that run is set to "Sponsored".
