### ISSUE TITLE
Ability for teams to forfeit

### ISSUE THREAD

**Issue by gaeldemarseille** [speedcontrol/nodecg-speedcontrol#44]
In a context of online races, a runner (or team) might forfeit the race.
It would be nice to actually have that information, I think there's 2 way to make it:
 - modifying teamFinishTimes in the timer object to have a status field (or using the state field which so far is just a copy of of the state of the main timer object at the time of finishing
- adding a teamQuitTimes field to the timer object as done in this really dirty commit gaeldemarseille@b732fc96c7651574d8c3ddba830ad3a7e5645440

**Comment by zoton2** [comment]
Added in `dev` branch; decided to go with the first option so everything is still identical except the `state` field in the `teamFinishTimes` is now either `completed` or `forfeit` depending on which has been done.
