### ISSUE TITLE
Remove Markdown on horaro import when not desired

### ISSUE THREAD

**Issue by gaeldemarseille** [speedcontrol/nodecg-speedcontrol#61]
An horaro column with `C:\Users\Shadow\Desktop\Tweet Pics\The_Simpsons_Hit_and_Run_cover.png` as value will be imported as `C:\Users\Shadow\Desktop\Tweet Pics\TheSimpsonsHitandRun_cover.png` and in this case it's obsiouly not desired

EDIT: value on horaro json is actually `C:\\Users\\Shadow\\Desktop\\Tweet Pics\\The_Simpsons_Hit_and_Run_cover.png` but was entered and is display on horaro without double \

**Comment by zoton2** [comment]
Because of the edge case-iness of this I think I'll put in an option to disable markdown parsing for a certain custom column.

**Comment by zoton2** [comment]
Added in `dev` branch, the `customData` object can now take a boolean, `ignoreMarkdown`.
